// mealsData.js
export const mealsData = [
    { name: 'Яблуко', calories: 52 },
    { name: 'Банан', calories: 96 },
    { name: 'Огірок', calories: 15 },
    { name: 'Вода', calories: 0 },
    { name: 'Хліб', calories: 265 },
    { name: 'Яйце', calories: 155 },
    { name: 'Молоко', calories: 42 },
    { name: 'Сир', calories: 402 },
    { name: 'Курка', calories: 165 },
    { name: 'Лосось', calories: 208 },
    { name: 'Картопля', calories: 77 },
    { name: 'Помідор', calories: 18 },
    { name: 'Морква', calories: 41 },
    { name: 'Шпинат', calories: 23 },
    { name: 'Горох', calories: 81 },
    { name: 'Броколі', calories: 34 },
    { name: 'Печиво', calories: 502 },
    { name: 'Шоколад', calories: 546 },
    { name: 'Апельсин', calories: 47 },
    { name: 'Груша', calories: 57 },
    { name: 'Вишня', calories: 50 },
    { name: 'Авокадо', calories: 160 },
    { name: 'Гречка', calories: 343 },
    { name: 'Рис', calories: 130 },
    { name: 'Квасоля', calories: 127 },
    { name: 'Суп курячий', calories: 60 },
    { name: 'Салат', calories: 15 },
    { name: 'Піца', calories: 285 },
    { name: 'Паста', calories: 131 },
    { name: 'Сік яблучний', calories: 46 },
    { name: 'Морозиво', calories: 207 },
    { name: 'Кавун', calories: 30 },
    { name: 'Часник', calories: 149 },
    { name: 'Чизкейк', calories: 321 },
    { name: 'Пюре', calories: 214 },
    { name: 'Буряк', calories: 43 },
    { name: 'Цибуля', calories: 40 },
    { name: 'Сирники', calories: 228 },
    { name: 'Мигдаль', calories: 579 },
    { name: 'Горіхи (волоський)', calories: 654 },
    { name: 'Кеш’ю', calories: 553 },
    { name: 'Персик', calories: 39 },
    { name: 'Кавун', calories: 30 },
    { name: 'Томати чері', calories: 18 }
];
